### ISSUE TITLE
ModuleNotFoundError: No module named 'DCNv3'

### ISSUE THREAD

**Issue by ghost** [ViTAE-Transformer/SAMRS#12]
感谢您开源的代码，我希望运行test_gpu.py但是报错了，请问您有遇到这个 问题吗

(oneformer) lscsc@lscsc-System-Product-Name:SAMRS/Pretraining and Finetuning/End_to_End$ CUDA_VISIBLE_DEVICES=0 python test_gpu.py --backbone 'vit_b'  --dataset 'potsdam' --ms 'False' --mode 'test'  --resume /media/lscsc/nas/yihan/SegAN/SAMRS/
Pretraining and Finetuning/weight/vit_b_samrs_mae_clip_checkpoint-1599.pth --save_path /media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining an
d Finetuning/Encoder_Decoder/output
Traceback (most recent call last):
  File "test_gpu.py", line 14, in <module>
    from models import SemsegFinetuneFramework
  File "/media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining and Finetuning/End_to_End/models.py", line 9, in <module>
    from backbone.intern_image import InternImage
  File "/media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining and Finetuning/End_to_End/backbone/intern_image.py", line 18, in <module>
    from .ops_dcnv3 import modules as opsm
  File "/media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining and Finetuning/End_to_End/backbone/ops_dcnv3/modules/__init__.py", line 7, in <module>
    from .dcnv3 import DCNv3, DCNv3_pytorch
  File "/media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining and Finetuning/End_to_End/backbone/ops_dcnv3/modules/dcnv3.py", line 16, in <module>
    from ..functions import DCNv3Function, dcnv3_core_pytorch
  File "/media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining and Finetuning/End_to_End/backbone/ops_dcnv3/functions/__init__.py", line 7, in <module>
    from .dcnv3_func import DCNv3Function, dcnv3_core_pytorch
  File "/media/lscsc/nas/yihan/SegAN/SAMRS/Pretraining and Finetuning/End_to_End/backbone/ops_dcnv3/functions/dcnv3_func.py", line 16, in <module>
    import DCNv3
ModuleNotFoundError: No module named 'DCNv3'

**Comment by DotWang** [comment]
@Udrs 使用internimage时，DCNv3需要额外安装，详情参考internimage官方库。另外，这个开源的是分割预训练后的模型，讲道理是不应该拿来做直接测试的，得拿这个模型在数据集上先finetune一下，再去测试
